/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "gpio.h"

void delay(void)
{
	for(uint32_t i = 0 ; i < 500000 ; i ++);
}


int main(void)
{

	// LED GPIO configuration
	// Discovery kit with STM32F407VG MCU User manual: hardware and layout, LEDs
	// User LD4: green LED is a user LED connected to the I/O PD12 of the STM32F407VGT6

	// assign GPIO port base address
	GPIO_RegDef_t *pGPIOLed;
	pGPIOLed = GPIOD;

	// assign pin number
	uint8_t GPIO_PinNumber_Led = GPIO_PIN_NO_12;

    // reset
	GPIOD_REG_RESET();

	// enable peripheral clock
	GPIOD_PCLK_EN();

	// configure the LED peripheral register
	//1 . configure the mode of GPIO pin: output
	pGPIOLed->MODER &= ~( 3UL << (2 * GPIO_PinNumber_Led)); //clearing bits, UL represents unsigned long integer with 32 bits
	pGPIOLed->MODER |= (GPIO_MODE_OUT << (2 * GPIO_PinNumber_Led ) ); //setting to desired value

	//2. configure the output type: push-pull
	pGPIOLed->OTYPER &= ~( 1UL << GPIO_PinNumber_Led); //clearing bit
	pGPIOLed->OTYPER |= (GPIO_OP_TYPE_PP << GPIO_PinNumber_Led ); //setting to desired value

	//3. configure the output speed: low speed
	pGPIOLed->OSPEEDR &= ~( 3UL << ( 2 * GPIO_PinNumber_Led)); //clearing bits
	pGPIOLed->OSPEEDR |= (GPIO_SPEED_LOW << ( 2 * GPIO_PinNumber_Led) ); //setting to desired value

	//4. configure the pull-up/pull-down setting: no pull-up/pull-down
	pGPIOLed->PUPDR &= ~( 3UL << ( 2 * GPIO_PinNumber_Led)); //clearing bits
	pGPIOLed->PUPDR |= (GPIO_NO_PUPD << ( 2 * GPIO_PinNumber_Led) ); //setting to desired value


	/* Loop forever */
	while(1)
	{
		// toggle GPIO pin by writing 0/1 to the GPIO port output data register
		pGPIOLed->ODR  ^= ( 1UL << GPIO_PinNumber_Led);

		delay();
	}


	return 0;
}
