/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "gpio.h"
#include "timer.h"

uint32_t it1, it2, cycle_count;      // start and stop flag, cycle count

// for task
#define   SIZE 8	// Defining Array size
int sum (int[],int);
void multiply(int[],int[],int[],const int);

int x[SIZE] = {1,1,1,1,1,0,0,0}; // Input array 1
int y[SIZE] = {0,0,0,1,1,1,1,1}; // Input array 2
int p[SIZE]; // Product array
int s; //Summation result


int main(void)
{
    // assign TIM6 base address
	TIMx_RegDef_t *pTIM6;
	pTIM6 = TIM6;

    // reset
	TIM6_REG_RESET();

	TIM6_PCLK_EN(); // enable TIM6 clock

    // configure TIM6 registers
	pTIM6->PSC = 0; // set prescaler to be 0
	pTIM6->ARR = 65535; // set auto-reload register to be 0xFFFF

	pTIM6->CR1 |= 1 << 0; // set bit 0 CEN to enable timer in CR1 register

	it1 = TIM6->CNT;   // store current cycle-count in CNT register in a variable: start

	// code you want to measure cycle counts for
	multiply(x,y,p, SIZE);
	s = sum (p, SIZE);

	it2 = TIM6->CNT;    // store current cycle-count in CNT register in a variable: end

	cycle_count = it2 - it1; // derive the cycle-count difference: elapsed clock ticks, at SystemCoreClock

	TIM6->SR &= ~( 1 << 0);    //  clear bit 0 CEN to disable counter in CR1 register

    /* Loop forever */
	for(;;);
}

void multiply (int a[] , int b[], int c[], const int length)
{
	int i;

	for (i=0; i< length; i ++)
	c[i] = a [i] * b[i];  // multiply two numbers


}

int sum (int a[], const int length)
{
	int i, sum;
	sum =0;
	for (i = 0;i<length;i++)  // sum element
		sum = sum + a[i];

	return sum;

}
