/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdint.h>

// for cycle count
// Cortex-M4 technical reference manual: DWT Programmers Model, address
// ARMv7M Architecture Reference Manual: explanation of registers
volatile uint32_t *DWT_CTRL = (uint32_t *) 0xE0001000; // set CYCCNTENA, bit[0] to enable CYCCNT register, clear to disable
volatile uint32_t *DWT_CYCCNT = (uint32_t *) 0xE0001004; // When enabled, CYCCNT increments on each processor clock cycle
volatile uint32_t *DEMCR = (uint32_t *) 0xE000EDFC; //DEMCR: set TRCENA, bit[24] to enable trace, clear to disable

uint32_t it1, it2, cycle_count;      // start and stop flag, cycle count

// for task
#define   SIZE 8	// Defining Array size
int sum (int[],int);
void multiply(int[],int[],int[],const int);

int x[SIZE] = {1,1,1,1,1,0,0,0}; // Input array 1
int y[SIZE] = {0,0,0,1,1,1,1,1}; // Input array 2
int p[SIZE]; // Product array
int s; //Summation result


int main(void)
{
	// enable cycle count
	*DEMCR |=  0x01000000;     // enable trace, set bit 24
	*DWT_CYCCNT = 0;           // clear DWT cycle counter
	*DWT_CTRL |=  1;	// enable DWT cycle counter, set bit 0


	it1 = *DWT_CYCCNT;      // store current cycle-count in a variable: start

	// code you want to measure cycle counts for
	multiply(x,y,p, SIZE);
	s = sum (p, SIZE);

	it2 = *DWT_CYCCNT;    // store current cycle-count in a variable: end
	cycle_count = it2 - it1; // derive the cycle-count difference: elapsed clock ticks, at SystemCoreClock

	*DWT_CTRL |=  0;         // disable DWT cycle counter, clear bit 0

    /* Loop forever */
	for(;;);
}

void multiply (int a[] , int b[], int c[], const int length)
{
	int i;

	for (i=0; i< length; i ++)
	c[i] = a [i] * b[i];  // multiply two numbers


}

int sum (int a[], const int length)
{
	int i, sum;
	sum =0;
	for (i = 0;i<length;i++)  // sum element
		sum = sum + a[i];

	return sum;

}
