/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>


#define   SIZE 9	// Defining Array size

int sum(int[], const int);
void multiply(int[], int[], int[], const int);


int x[SIZE] = {1,1,1,1,0,0,0,1,0}; // Input array 1
int y[SIZE] = {1,0,0,0,1,1,1,1,0}; // Input array 2
int p[SIZE]; // Product array
int s; //Summation result


int main(void)
{   // MAC operation
	// element-wise multiplication of two arrays of numbers and add the products
	multiply(x,y,p, SIZE);
	s = sum (p, SIZE);

    /* Loop forever */
	for(;;);
}

void multiply (int a[] , int b[], int c[], const int length)
{
	int i;

	for (i=0; i<length; i++) {
		c[i] = a[i] * b[i];  // multiply two numbers
	}
}

int sum (int a[], const int length)
{
	int i;
	int sum = 0;
	for (i=0;i<length;i++) { // sum element
		sum = sum + a[i];
	}

	return sum;

}

